name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.6.0
      with:
        hugo-version: "latest"
        extended: true
    - name: Prereq
      run: |
        sudo snap install dart-sass
        npm i -D postcss postcss-cli autoprefixer postcss-import
    - name: Build and Deploy
      run: |
          hugo -F --cleanDestinationDir
          mkdir -p public
          cp -r public/* ./

